---

- block:

  - name: "install pre-requisites"
    apt:
      pkg:
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg2"
        - "software-properties-common"
        - "python3-setuptools"
        - "python3-pip"

  - name: "update alternative to python3"
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python3

  - name: "ensure latest pip"
    pip:
      name: "pip"
      state: latest

  - name: "copy docker GPG key"
    copy:
      src: "docker.gpg.key"
      dest: "/tmp"
      force: yes

  - name: "install docker GPG key"
    apt_key:
      file: "/tmp/docker.gpg.key"
      state: present

  - name: "add docker repo"
    apt_repository:
      repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      filename: "docker.list"
      state: present

  - name: "install docker-ce"
    apt:
      pkg:
        - "docker-ce"

  - name: "install required pip modules"
    pip:
      name:
        - "docker-compose"
        - "lxml"
      state: latest

  - name: "ensure /srv/docker"
    file:
      path: "/srv/docker"
      state: directory

  - name: "Set docker daemon options"
    copy:
      src: "daemon.json"
      dest: "/etc/docker"
      force: yes
    notify:
      - "Reload systemd"
      - "Restart docker"

  become: true
  tags:
    - "gnar-docker"
