---

- block:

  - name: "install pre-requisites"
    apt:
      pkg:
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg2"
        - "software-properties-common"
        - "python3-setuptools"
        - "python3-pip"
        - "python3-dev"
        - "build-essential"
        - "libssl-dev"
        - "libffi-dev"
        - "libxml2-dev"
        - "libxslt-dev"
        - "zlib1g-dev"

  - name: "update alternative to python3"
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python3

  - name: "ensure latest pip"
    pip:
      name: "pip"
      state: latest

  - name: "copy docker GPG key"
    copy:
      src: "docker.gpg.key"
      dest: "/tmp"
      force: yes

  - name: "install docker GPG key"
    apt_key:
      file: "/tmp/docker.gpg.key"
      state: present

  - name: "add docker repo"
    apt_repository:
      repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      filename: "docker.list"
      state: present

  - name: "install docker-ce"
    apt:
      pkg:
        - "docker-ce"

  - name: "install required pip modules"
    pip:
      name:
        - "docker-compose"
        - "lxml"
      state: latest

  - name: "ensure /srv/docker"
    file:
      path: "/srv/docker"
      state: directory

  - name: "start docker after srv mount"
    lineinfile:
      path: "/etc/systemd/system/multi-user.target.wants/docker.service"
      regexp: '^(After=(?!.*srv.mount).*)$'
      line: '\1 srv.mount'
      backrefs: yes
    notify:
      - "Reload systemd"

  - name: "start docker only if srv mount exists"
    lineinfile:
      path: "/etc/systemd/system/multi-user.target.wants/docker.service"
      regexp: '^(Requires=(?!.*srv.mount).*)$'
      line: '\1 srv.mount'
      backrefs: yes
    notify:
      - "Reload systemd"

  - name: "Set docker daemon options"
    copy:
      src: "daemon.json"
      dest: "/etc/docker"
      force: yes
    notify:
      - "Reload systemd"
      - "Restart docker"

  become: true
  tags:
    - "docker-host"
